compressionLevel: mixed

enableGlobalCache: true

packageExtensions:
  "@irys/arweave@*":
    dependencies:
      bn.js: "*"
  "@irys/sdk@*":
    dependencies:
      bn.js: "*"
      borsh: "*"
      js-sha3: "*"
  "@keystonehq/bc-ur-registry@*":
    dependencies:
      buffer: ^6.0.3
  "@metaplex-foundation/mpl-candy-guard@*":
    dependencies:
      debug: "*"
  "@particle-network/auth@*":
    dependencies:
      crypto-js: ^4.0.0
      events: ^3.3.0
  "@particle-network/solana-wallet@*":
    dependencies:
      bs58: ^5.0.0
      buffer: ^6.0.3
      events: ^3.3.0
  "@solana/wallet-adapter-solflare@*":
    dependencies:
      "@solana/wallet-standard-features": ^1.2.0
      "@wallet-standard/features": ^1.0.3
  "@solana/wallet-standard-wallet-adapter-base@*":
    dependencies:
      bs58: ^5.0.0
  "@toruslabs/solana-embed@*":
    dependencies:
      "@babel/runtime": ^7.24.7
  "@trezor/connect-web@*":
    dependencies:
      tslib: ^2.6.3
  arbundles@*:
    dependencies:
      bn.js: "*"
  jotai@*:
    dependencies:
      "@babel/template": "*"
  node-stdlib-browser@*:
    dependencies:
      qs: "*"
