/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/~__root'
import { Route as IndexImport } from './routes/~index'
import { Route as ProfileIndexImport } from './routes/~profile/~index'
import { Route as LufiIndexImport } from './routes/~lufi/~index'
import { Route as LbpSwapPoolAddressImport } from './routes/~lbp/~swap/~$poolAddress'
import { Route as FastLaunchSwapPoolAddressImport } from './routes/~fast-launch/~swap/~$poolAddress'
import { Route as LbpCreateIndexImport } from './routes/~lbp/~create/~index'
import { Route as LaunchesPumpIndexImport } from './routes/~launches/~pump/~index'
import { Route as LaunchesLbpIndexImport } from './routes/~launches/~lbp/~index'
import { Route as FastLaunchCreateIndexImport } from './routes/~fast-launch/~create/~index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const LufiIndexRoute = LufiIndexImport.update({
  id: '/lufi/',
  path: '/lufi/',
  getParentRoute: () => rootRoute,
} as any)

const LbpSwapPoolAddressRoute = LbpSwapPoolAddressImport.update({
  id: '/lbp/swap/$poolAddress',
  path: '/lbp/swap/$poolAddress',
  getParentRoute: () => rootRoute,
} as any)

const FastLaunchSwapPoolAddressRoute = FastLaunchSwapPoolAddressImport.update({
  id: '/fast-launch/swap/$poolAddress',
  path: '/fast-launch/swap/$poolAddress',
  getParentRoute: () => rootRoute,
} as any)

const LbpCreateIndexRoute = LbpCreateIndexImport.update({
  id: '/lbp/create/',
  path: '/lbp/create/',
  getParentRoute: () => rootRoute,
} as any)

const LaunchesPumpIndexRoute = LaunchesPumpIndexImport.update({
  id: '/launches/pump/',
  path: '/launches/pump/',
  getParentRoute: () => rootRoute,
} as any)

const LaunchesLbpIndexRoute = LaunchesLbpIndexImport.update({
  id: '/launches/lbp/',
  path: '/launches/lbp/',
  getParentRoute: () => rootRoute,
} as any)

const FastLaunchCreateIndexRoute = FastLaunchCreateIndexImport.update({
  id: '/fast-launch/create/',
  path: '/fast-launch/create/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/lufi/': {
      id: '/lufi/'
      path: '/lufi'
      fullPath: '/lufi'
      preLoaderRoute: typeof LufiIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/fast-launch/create/': {
      id: '/fast-launch/create/'
      path: '/fast-launch/create'
      fullPath: '/fast-launch/create'
      preLoaderRoute: typeof FastLaunchCreateIndexImport
      parentRoute: typeof rootRoute
    }
    '/launches/lbp/': {
      id: '/launches/lbp/'
      path: '/launches/lbp'
      fullPath: '/launches/lbp'
      preLoaderRoute: typeof LaunchesLbpIndexImport
      parentRoute: typeof rootRoute
    }
    '/launches/pump/': {
      id: '/launches/pump/'
      path: '/launches/pump'
      fullPath: '/launches/pump'
      preLoaderRoute: typeof LaunchesPumpIndexImport
      parentRoute: typeof rootRoute
    }
    '/lbp/create/': {
      id: '/lbp/create/'
      path: '/lbp/create'
      fullPath: '/lbp/create'
      preLoaderRoute: typeof LbpCreateIndexImport
      parentRoute: typeof rootRoute
    }
    '/fast-launch/swap/$poolAddress': {
      id: '/fast-launch/swap/$poolAddress'
      path: '/fast-launch/swap/$poolAddress'
      fullPath: '/fast-launch/swap/$poolAddress'
      preLoaderRoute: typeof FastLaunchSwapPoolAddressImport
      parentRoute: typeof rootRoute
    }
    '/lbp/swap/$poolAddress': {
      id: '/lbp/swap/$poolAddress'
      path: '/lbp/swap/$poolAddress'
      fullPath: '/lbp/swap/$poolAddress'
      preLoaderRoute: typeof LbpSwapPoolAddressImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lufi': typeof LufiIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/fast-launch/create': typeof FastLaunchCreateIndexRoute
  '/launches/lbp': typeof LaunchesLbpIndexRoute
  '/launches/pump': typeof LaunchesPumpIndexRoute
  '/lbp/create': typeof LbpCreateIndexRoute
  '/fast-launch/swap/$poolAddress': typeof FastLaunchSwapPoolAddressRoute
  '/lbp/swap/$poolAddress': typeof LbpSwapPoolAddressRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lufi': typeof LufiIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/fast-launch/create': typeof FastLaunchCreateIndexRoute
  '/launches/lbp': typeof LaunchesLbpIndexRoute
  '/launches/pump': typeof LaunchesPumpIndexRoute
  '/lbp/create': typeof LbpCreateIndexRoute
  '/fast-launch/swap/$poolAddress': typeof FastLaunchSwapPoolAddressRoute
  '/lbp/swap/$poolAddress': typeof LbpSwapPoolAddressRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/lufi/': typeof LufiIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/fast-launch/create/': typeof FastLaunchCreateIndexRoute
  '/launches/lbp/': typeof LaunchesLbpIndexRoute
  '/launches/pump/': typeof LaunchesPumpIndexRoute
  '/lbp/create/': typeof LbpCreateIndexRoute
  '/fast-launch/swap/$poolAddress': typeof FastLaunchSwapPoolAddressRoute
  '/lbp/swap/$poolAddress': typeof LbpSwapPoolAddressRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lufi'
    | '/profile'
    | '/fast-launch/create'
    | '/launches/lbp'
    | '/launches/pump'
    | '/lbp/create'
    | '/fast-launch/swap/$poolAddress'
    | '/lbp/swap/$poolAddress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lufi'
    | '/profile'
    | '/fast-launch/create'
    | '/launches/lbp'
    | '/launches/pump'
    | '/lbp/create'
    | '/fast-launch/swap/$poolAddress'
    | '/lbp/swap/$poolAddress'
  id:
    | '__root__'
    | '/'
    | '/lufi/'
    | '/profile/'
    | '/fast-launch/create/'
    | '/launches/lbp/'
    | '/launches/pump/'
    | '/lbp/create/'
    | '/fast-launch/swap/$poolAddress'
    | '/lbp/swap/$poolAddress'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LufiIndexRoute: typeof LufiIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  FastLaunchCreateIndexRoute: typeof FastLaunchCreateIndexRoute
  LaunchesLbpIndexRoute: typeof LaunchesLbpIndexRoute
  LaunchesPumpIndexRoute: typeof LaunchesPumpIndexRoute
  LbpCreateIndexRoute: typeof LbpCreateIndexRoute
  FastLaunchSwapPoolAddressRoute: typeof FastLaunchSwapPoolAddressRoute
  LbpSwapPoolAddressRoute: typeof LbpSwapPoolAddressRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LufiIndexRoute: LufiIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  FastLaunchCreateIndexRoute: FastLaunchCreateIndexRoute,
  LaunchesLbpIndexRoute: LaunchesLbpIndexRoute,
  LaunchesPumpIndexRoute: LaunchesPumpIndexRoute,
  LbpCreateIndexRoute: LbpCreateIndexRoute,
  FastLaunchSwapPoolAddressRoute: FastLaunchSwapPoolAddressRoute,
  LbpSwapPoolAddressRoute: LbpSwapPoolAddressRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "~__root.tsx",
      "children": [
        "/",
        "/lufi/",
        "/profile/",
        "/fast-launch/create/",
        "/launches/lbp/",
        "/launches/pump/",
        "/lbp/create/",
        "/fast-launch/swap/$poolAddress",
        "/lbp/swap/$poolAddress"
      ]
    },
    "/": {
      "filePath": "~index.tsx"
    },
    "/lufi/": {
      "filePath": "~lufi/~index.tsx"
    },
    "/profile/": {
      "filePath": "~profile/~index.tsx"
    },
    "/fast-launch/create/": {
      "filePath": "~fast-launch/~create/~index.tsx"
    },
    "/launches/lbp/": {
      "filePath": "~launches/~lbp/~index.tsx"
    },
    "/launches/pump/": {
      "filePath": "~launches/~pump/~index.tsx"
    },
    "/lbp/create/": {
      "filePath": "~lbp/~create/~index.tsx"
    },
    "/fast-launch/swap/$poolAddress": {
      "filePath": "~fast-launch/~swap/~$poolAddress.tsx"
    },
    "/lbp/swap/$poolAddress": {
      "filePath": "~lbp/~swap/~$poolAddress.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
